### ISSUE TITLE
libuv version?

### ISSUE THREAD

**Issue by ernstp** [stevedesmond-ca/dotnet-arm#1]
Hi! Nice stuff, helping me a bit on the way on something similar.

However I don't see how your libuv version/checkout/build affects the resulting corehost distribution in anyway... ?

**Comment by SteveDesmond-ca** [comment]
Yep, you're right -- around the same time I was working on that, they got the official CI packages up on myget, so corehost just pulls those down, and I never cleaned this part up.

I would like to get a more self-contained, end-to-end build, though. Apparently the team is working on that too.

**Comment by ernstp** [comment]
Do you know if it find a binary libuv somewhere or does it compile it from source?

**Comment by SteveDesmond-ca** [comment]
https://github.com/aspnet/libuv-build builds it from source, uploads it to myget, then https://github.com/aspnet/libuv-package takes those and combines them for the core-setup build process

**Comment by SteveDesmond-ca** [comment]
Holding off on this as the official build pipeline improvements should fix this
