### ISSUE TITLE
don't install g++-arm-linux-gnueabihf

### ISSUE THREAD

**Issue by wangweinjcn** [stevedesmond-ca/dotnet-arm#6]
environment:
 raspberry pi3 ，ubuntu mate 16.04 
![image](https://cloud.githubusercontent.com/assets/698874/26542675/7a9515ca-448d-11e7-92fe-2a61d618b1ea.png)

**Comment by SteveDesmond-ca** [comment]
It looks like you're trying to build *on* your Raspberry Pi. This is not supported -- .NET Core can only be built on x64.
