### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by eshess** [stevedesmond-ca/dotnet-arm#7]
build-coreclr produces:
grep: ../core-setup/pkg/projects/Microsoft.NETCore.App/project.json.template: No such file or directory

build-roslyn produces:
make: *** No role to make target 'all'. Stop.

build-cli produces:
./run-build.sh: line 109: syntax error near unexpected token `)'

**Comment by SteveDesmond-ca** [comment]
Yeah, I've largely stopped maintaining this now that there are official builds. I'll add a note to the readme.

**Comment by eshess** [comment]
I figured that was probably the case. Was the SDK component functional on ARM when you had it working? It'd be nice to be able to do dotnet build/restore/etc even if it's not officially supported.

**Comment by SteveDesmond-ca** [comment]
It built but never ran properly. Part of the problem is ARM chips aren't made for things like compiling, so a `dotnet run` of hello world takes >30sec. I kind of want to get it up and running again now though, so I'll leave this open as a reminder to myself.

**Comment by SteveDesmond-ca** [comment]
https://github.com/stevedesmond-ca/dotnet-arm/commit/d74d6082cbcae4b62c8dfe7d50e970512b3aa6ca
